#!/usr/bin/env bash
#Update package list and install Nginx
apt update
apt install nginx -y

#Configure Nginx to listen on port 80 and return "Hello World!"
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location / {
                add_header X-Served-By $hostname;
                return 200 "Hello World!\n";
        }
}' > /etc/nginx/sites-available/default


#Restart Nginx to apply changes
service nginx restart
