#!/usr/bin/env bash
# Installing and configuring HAproxy on lb-01 server
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" > /etc/default/haproxy
echo "
backend my_backend
	balance roundrobin
	server 390228-web-01 100.25.102.121:80 check
	server 390228-web-02 54.162.98.138:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
