#!/usr/bin/env bash
#clock time for 12hours 59 minutes
hours=0
minutes=1
while [ "$hours" -le 12 ]
do
    echo "Hour: $hours"
    while [ "$minutes" -le 59 ]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    minutes=1
    ((hours++))
done
